//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoogleApiResponse.RouteDetailsService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RouteDetailsService.IRouteDetailsService")]
    public interface IRouteDetailsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRouteDetailsService/GetStreetData", ReplyAction="http://tempuri.org/IRouteDetailsService/GetStreetDataResponse")]
        string[] GetStreetData(string requestUri);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRouteDetailsService/GetStreetData", ReplyAction="http://tempuri.org/IRouteDetailsService/GetStreetDataResponse")]
        System.Threading.Tasks.Task<string[]> GetStreetDataAsync(string requestUri);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRouteDetailsServiceChannel : GoogleApiResponse.RouteDetailsService.IRouteDetailsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RouteDetailsServiceClient : System.ServiceModel.ClientBase<GoogleApiResponse.RouteDetailsService.IRouteDetailsService>, GoogleApiResponse.RouteDetailsService.IRouteDetailsService {
        
        public RouteDetailsServiceClient() {
        }
        
        public RouteDetailsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RouteDetailsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RouteDetailsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RouteDetailsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] GetStreetData(string requestUri) {
            return base.Channel.GetStreetData(requestUri);
        }
        
        public System.Threading.Tasks.Task<string[]> GetStreetDataAsync(string requestUri) {
            return base.Channel.GetStreetDataAsync(requestUri);
        }
    }
}
