//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoogleApiResponse.RouteDetailsService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StreetDetails", Namespace="http://schemas.datacontract.org/2004/07/RouteDetails")]
    [System.SerializableAttribute()]
    public partial class StreetDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string stNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GoogleApiResponse.RouteDetailsService.Step stepField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string stName {
            get {
                return this.stNameField;
            }
            set {
                if ((object.ReferenceEquals(this.stNameField, value) != true)) {
                    this.stNameField = value;
                    this.RaisePropertyChanged("stName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GoogleApiResponse.RouteDetailsService.Step step {
            get {
                return this.stepField;
            }
            set {
                if ((object.ReferenceEquals(this.stepField, value) != true)) {
                    this.stepField = value;
                    this.RaisePropertyChanged("step");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Step", Namespace="http://schemas.datacontract.org/2004/07/RouteDetails")]
    [System.SerializableAttribute()]
    public partial class Step : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GoogleApiResponse.RouteDetailsService.Distance2 distanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GoogleApiResponse.RouteDetailsService.Duration2 durationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GoogleApiResponse.RouteDetailsService.EndLocation2 end_locationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string html_instructionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string maneuverField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GoogleApiResponse.RouteDetailsService.Polyline polylineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GoogleApiResponse.RouteDetailsService.StartLocation2 start_locationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string travel_modeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GoogleApiResponse.RouteDetailsService.Distance2 distance {
            get {
                return this.distanceField;
            }
            set {
                if ((object.ReferenceEquals(this.distanceField, value) != true)) {
                    this.distanceField = value;
                    this.RaisePropertyChanged("distance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GoogleApiResponse.RouteDetailsService.Duration2 duration {
            get {
                return this.durationField;
            }
            set {
                if ((object.ReferenceEquals(this.durationField, value) != true)) {
                    this.durationField = value;
                    this.RaisePropertyChanged("duration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GoogleApiResponse.RouteDetailsService.EndLocation2 end_location {
            get {
                return this.end_locationField;
            }
            set {
                if ((object.ReferenceEquals(this.end_locationField, value) != true)) {
                    this.end_locationField = value;
                    this.RaisePropertyChanged("end_location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string html_instructions {
            get {
                return this.html_instructionsField;
            }
            set {
                if ((object.ReferenceEquals(this.html_instructionsField, value) != true)) {
                    this.html_instructionsField = value;
                    this.RaisePropertyChanged("html_instructions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string maneuver {
            get {
                return this.maneuverField;
            }
            set {
                if ((object.ReferenceEquals(this.maneuverField, value) != true)) {
                    this.maneuverField = value;
                    this.RaisePropertyChanged("maneuver");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GoogleApiResponse.RouteDetailsService.Polyline polyline {
            get {
                return this.polylineField;
            }
            set {
                if ((object.ReferenceEquals(this.polylineField, value) != true)) {
                    this.polylineField = value;
                    this.RaisePropertyChanged("polyline");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GoogleApiResponse.RouteDetailsService.StartLocation2 start_location {
            get {
                return this.start_locationField;
            }
            set {
                if ((object.ReferenceEquals(this.start_locationField, value) != true)) {
                    this.start_locationField = value;
                    this.RaisePropertyChanged("start_location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string travel_mode {
            get {
                return this.travel_modeField;
            }
            set {
                if ((object.ReferenceEquals(this.travel_modeField, value) != true)) {
                    this.travel_modeField = value;
                    this.RaisePropertyChanged("travel_mode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Distance2", Namespace="http://schemas.datacontract.org/2004/07/RouteDetails")]
    [System.SerializableAttribute()]
    public partial class Distance2 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string textField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int valueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string text {
            get {
                return this.textField;
            }
            set {
                if ((object.ReferenceEquals(this.textField, value) != true)) {
                    this.textField = value;
                    this.RaisePropertyChanged("text");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int value {
            get {
                return this.valueField;
            }
            set {
                if ((this.valueField.Equals(value) != true)) {
                    this.valueField = value;
                    this.RaisePropertyChanged("value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Duration2", Namespace="http://schemas.datacontract.org/2004/07/RouteDetails")]
    [System.SerializableAttribute()]
    public partial class Duration2 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string textField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int valueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string text {
            get {
                return this.textField;
            }
            set {
                if ((object.ReferenceEquals(this.textField, value) != true)) {
                    this.textField = value;
                    this.RaisePropertyChanged("text");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int value {
            get {
                return this.valueField;
            }
            set {
                if ((this.valueField.Equals(value) != true)) {
                    this.valueField = value;
                    this.RaisePropertyChanged("value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EndLocation2", Namespace="http://schemas.datacontract.org/2004/07/RouteDetails")]
    [System.SerializableAttribute()]
    public partial class EndLocation2 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double latField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double lngField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double lat {
            get {
                return this.latField;
            }
            set {
                if ((this.latField.Equals(value) != true)) {
                    this.latField = value;
                    this.RaisePropertyChanged("lat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double lng {
            get {
                return this.lngField;
            }
            set {
                if ((this.lngField.Equals(value) != true)) {
                    this.lngField = value;
                    this.RaisePropertyChanged("lng");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Polyline", Namespace="http://schemas.datacontract.org/2004/07/RouteDetails")]
    [System.SerializableAttribute()]
    public partial class Polyline : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pointsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string points {
            get {
                return this.pointsField;
            }
            set {
                if ((object.ReferenceEquals(this.pointsField, value) != true)) {
                    this.pointsField = value;
                    this.RaisePropertyChanged("points");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StartLocation2", Namespace="http://schemas.datacontract.org/2004/07/RouteDetails")]
    [System.SerializableAttribute()]
    public partial class StartLocation2 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double latField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double lngField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double lat {
            get {
                return this.latField;
            }
            set {
                if ((this.latField.Equals(value) != true)) {
                    this.latField = value;
                    this.RaisePropertyChanged("lat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double lng {
            get {
                return this.lngField;
            }
            set {
                if ((this.lngField.Equals(value) != true)) {
                    this.lngField = value;
                    this.RaisePropertyChanged("lng");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RouteDetailsService.IRouteDetailsService")]
    public interface IRouteDetailsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRouteDetailsService/GetStreetData", ReplyAction="http://tempuri.org/IRouteDetailsService/GetStreetDataResponse")]
        GoogleApiResponse.RouteDetailsService.StreetDetails[] GetStreetData(string requestUri);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRouteDetailsService/GetStreetData", ReplyAction="http://tempuri.org/IRouteDetailsService/GetStreetDataResponse")]
        System.Threading.Tasks.Task<GoogleApiResponse.RouteDetailsService.StreetDetails[]> GetStreetDataAsync(string requestUri);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRouteDetailsService/GetRouteSafety", ReplyAction="http://tempuri.org/IRouteDetailsService/GetRouteSafetyResponse")]
        int[] GetRouteSafety(string requestUri);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRouteDetailsService/GetRouteSafety", ReplyAction="http://tempuri.org/IRouteDetailsService/GetRouteSafetyResponse")]
        System.Threading.Tasks.Task<int[]> GetRouteSafetyAsync(string requestUri);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRouteDetailsServiceChannel : GoogleApiResponse.RouteDetailsService.IRouteDetailsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RouteDetailsServiceClient : System.ServiceModel.ClientBase<GoogleApiResponse.RouteDetailsService.IRouteDetailsService>, GoogleApiResponse.RouteDetailsService.IRouteDetailsService {
        
        public RouteDetailsServiceClient() {
        }
        
        public RouteDetailsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RouteDetailsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RouteDetailsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RouteDetailsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GoogleApiResponse.RouteDetailsService.StreetDetails[] GetStreetData(string requestUri) {
            return base.Channel.GetStreetData(requestUri);
        }
        
        public System.Threading.Tasks.Task<GoogleApiResponse.RouteDetailsService.StreetDetails[]> GetStreetDataAsync(string requestUri) {
            return base.Channel.GetStreetDataAsync(requestUri);
        }
        
        public int[] GetRouteSafety(string requestUri) {
            return base.Channel.GetRouteSafety(requestUri);
        }
        
        public System.Threading.Tasks.Task<int[]> GetRouteSafetyAsync(string requestUri) {
            return base.Channel.GetRouteSafetyAsync(requestUri);
        }
    }
}
